spring:
  profiles:
    active: local
#  datasource:
#    url: jdbc:h2:mem:testdb
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: local
#  redis:
#    host: localhost
#    port: 6379
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
server:
  port: 8085
logging:
  level:
    root: INFO